version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/cafe
    depends_on:
      - mongo

  customer-services:
    build: ./customer-services
    ports:
      - "3005:3005"
    environment:
      - MONGO_URL=mongodb://mongo:27017/cafe
    depends_on:
      - mongo

  inventory-services:
    build: ./inventory-services
    ports:
      - "3004:3004"
    environment:
      - MONGO_URL=mongodb://mongo:27017/cafe
    depends_on:
      - mongo

  menu-services:
    build: ./menu-services
    ports:
      - "3001:3001"
    environment:
      - MONGO_URL=mongodb://mongo:27017/cafe
    depends_on:
      - mongo

  order-services:
    build: ./order-services
    ports:
      - "3002:3002"
    environment:
      - MONGO_URL=mongodb://mongo:27017/cafe
    depends_on:
      - mongo

  payment-services:
    build: ./payment-services
    ports:
      - "3003:3003"
    environment:
      - MONGO_URL=mongodb://mongo:27017/cafe
    depends_on:
      - mongo

volumes:
  mongo_data: