name: CI/CD Pipeline for API Gateway

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
        options: >-
          --health-cmd "echo 'db.runCommand({ ping: 1 })' | mongo --username root --password example --quiet"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./api-gateway

      - name: Run unit tests
        run: npm test
        working-directory: ./api-gateway

      - name: Build Docker image
        run: docker build -t your-dockerhub-username/api-gateway:latest .
        working-directory: ./api-gateway

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push your-dockerhub-username/api-gateway:latest

      - name: Clean up
        run: docker rmi your-dockerhub-username/api-gateway:latest